app:
  instance-id: ${APP_INSTANCE_ID}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

traffic-generator:
  control-base-url: ${TRAFFIC_GENERATOR_CONTROL_BASE_URL}
  target-base-url: ${TRAFFIC_GENERATOR_TARGET_BASE_URL}
  default-concurrency: ${TRAFFIC_GENERATOR_DEFAULT_CONCURRENCY:20}
