services:
  api-a:
    image: chocojipsa/timedeal-backend:latest
    env_file:
      - .env
    environment:
      APP_INSTANCE_ID: api-a
      SPRING_PROFILES_ACTIVE: prod
    expose:
      - "8080"
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx-api.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:8080"
    depends_on:
      - api-a
    restart: unless-stopped

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Xmx512m -XX:MaxRAMPercentage=50.0
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    mem_limit: 1g
