services:
  api-b:
    image: chocojipsa/timedeal-backend:${BACKEND_VERSION:-latest}
    env_file:
      - .env
    environment:
      APP_INSTANCE_ID: api-b
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    restart: unless-stopped

  dev-api:
    image: chocojipsa/timedeal-backend:${BACKEND_VERSION:-latest}
    env_file:
      - .env
    environment:
      APP_INSTANCE_ID: dev-api
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8082:8080"
    restart: unless-stopped

  worker:
    image: chocojipsa/timedeal-backend:${BACKEND_VERSION:-latest}
    env_file:
      - .env
    environment:
      APP_INSTANCE_ID: worker
      SPRING_PROFILES_ACTIVE: prod,worker
    restart: unless-stopped

  traffic-generator:
    image: chocojipsa/timedeal-backend:${BACKEND_VERSION:-latest}
    env_file:
      - .env
    environment:
      APP_INSTANCE_ID: traffic-generator
      SPRING_PROFILES_ACTIVE: prod,generator
    ports:
      - "8081:8080"
    restart: unless-stopped
